on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: innovation-nest-js   # set this to your application's name
  NODE_VERSION: '16.x'                # set this to the node version to use


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: yarn install and build
      run: |
        yarn install
        yarn run build

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}